version: 2
updates:
- package-ecosystem: gradle
  directory: "/finish/jar"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
- package-ecosystem: gradle
  directory: "/finish/war"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
- package-ecosystem: gradle
  directory: "/finish/ear"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
- package-ecosystem: gradle
  directory: "/start/jar"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
- package-ecosystem: gradle
  directory: "/start/war"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
- package-ecosystem: gradle
  directory: "/start/ear"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
